---
title: "Untitled"
author: "林茂廷"
date: "2022-10-31"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

在進行跨國GDP比較時，直覺做法會用匯率將比較對象的GDP均轉成相同幣別才進行比較。然而匯率波動不小，採取不同日期的匯率，此匯率GDP的金額也會不同而產生比較的差異。

另一個較為合理的比較是在比誰的GDP產值在該國能買的東西最多。比較時會先選定某些商品形成一籃子商品，再去調查比較國家在自己國內購買該籃商品的成本。假設此一籃子商品在台灣購入成本為$P_{tw}$，在美國的購入成本為$P_{us}$。令$GDP_{tw}$為台灣的名目GDP, 則此金額可購買一籃商品的籃數為$GDP_{tw}/P_{tw}$單位，要和美國比較的話，可以把它乘上美國的此一籃子商品價格(令為$P_{us}$)，即形成台灣GDP的購買力相當於在美國擁有$P_{us}GDP_{tw}/P_{tw}$美金。

$$台灣GDP\ PPP以美元計 ＝台灣GDP\times {美國物價 \over 台灣物價}$$

PPP全名為購買力平價說(Purchasing Power Parity)，此理論假設在無任何交易障礙下，一元本國幣在本國能買得起的東西數量，跟它換成外幣到外國買應該相同，即有相同的購買力。以台幣兌美元為例，假設台灣某商品物價10元，100元台幣可以買10件, 同件商品在美國若為2美元且100元台幣可兌換M美元，則台幣100元換成M美元去買同件商品可以買M/2件。符合購買力平價的匯率會使$M／2＝10$，即在美國買的件數和在台灣買是一樣多。此符合PPP的匯率值$M=10/2$即為台灣物價除以美國物價。在比較台、美兩國GDP購買力時，台灣GDP乘上$P_{us}/P_{tw}$相對價格比，而此相對價格若以台幣兌美元購買力平價匯率M來表示的話，GDP PPP也可以寫成
$$台灣GDP\ PPP以美元計 ＝ {台灣GDP \over 購買力平價下台幣兌美元匯率}$$


在相同名目GDP下，物價較便宜的國家其GDP的實質購買力較高。圖XXX是2017年十個國家分別在名目人均GDP及實質人均GDP（以人均GDP PPP衡量）的全球排名表現。台灣在名目GDP排名第三十名，但因台灣物價相對上低，實質GDP排名反而更高，上升到第26名，超越物價水準高的法國和英國。
